server:
  port: 8080

msb:
  redis:
    ip: 150.158.188.28
    port: 6379
    password: Newtouch1!
    database: 0

spring:
  cache:
    type: redis
  redis:
    host: ${msb.redis.ip}
    port: ${msb.redis.port}
    password: ${msb.redis.password}

j2cache:
  open-spring-cache: true
  cache-clean-mode: passive
  allow-null-values: true
  # ?? redis ????? lettuce, ????? jedis
  redis-client: lettuce
  # ???????false ??????????
  l2-cache-open: true
  # ???????j2cache? 1.3.0 ?????? JGroups ? redis pub/sub ?????????????
  # ????????? redis ???????????????????????????
  broadcast: net.oschina.j2cache.cache.support.redis.SpringRedisPubSubPolicy
  # broadcast: jgroups
  L1:
    # ?????????? caffeine
    provider_class: caffeine
  L2:
    # ?????????? redis
    provider_class: net.oschina.j2cache.cache.support.redis.SpringRedisProvider
    config_section: lettuce
  sync_ttl_to_redis: true
  default_cache_null_object: false
  serialization: fst
caffeine:
  # ?????????????
  properties: /caffeine.properties
# lettuce ? redis ???????????? jedis??????? redis ? java ???
lettuce:
  mode: single
  namespace:
  storage: generic
  channel: j2cache
  scheme: redis
  hosts: ${msb.redis.ip}:${msb.redis.port}
  password: ${msb.redis.password}
  database: ${msb.redis.database}
  sentinelMasterId:
  maxTotal: 100
  maxIdle: 10
  minIdle: 10
  timeout: 10000




